[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "mobile-price-class-mlops"
version = "0.1.0"
description = "Clasificación de teléfonos por rango de precio"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-p no:cacheprovider"
testpaths = ["tests"]
